#ifndef __SMK_FLASH_CONFIG_H
#define __SMK_FLASH_CONFIG_H


#define SMK_CONFIG_USER_FLASH_START_ADDR 0x00080000 // user flash start at 512k 
#define SMK_CONFIG_KEYMAP_START_ADDR (SMK_CONFIG_USER_FLASH_START_ADDR)
#define SMK_CONFIG_KEYMAP_LENGTH 0x00001000 // 4k for keymap

#endif